// ============================================================
// Dual-mode Authentication Wrapper
// Validates: Requirements 9.3
// ============================================================
// Switches between Cognito (global) and self-hosted Auth Service (china)
// Runtime config is loaded from /console/config.json (generated by CDK).

import { signIn as amplifySignIn, signOut as amplifySignOut, fetchAuthSession } from 'aws-amplify/auth';
import { Amplify } from 'aws-amplify';

// ---- Runtime Configuration ----
// Loaded from /console/config.json at startup. Falls back to VITE_* env vars for local dev.

interface RuntimeConfig {
  authMode: 'global' | 'china' | 'dev';
  cognitoUserPoolId?: string;
  cognitoClientId?: string;
  apiBaseUrl?: string;
  jwksUri?: string;
}

let _config: RuntimeConfig | null = null;
let _configPromise: Promise<RuntimeConfig> | null = null;

async function fetchRuntimeConfig(): Promise<RuntimeConfig> {
  // Try loading /console/config.json (deployed by CDK)
  try {
    const resp = await fetch('/console/config.json');
    if (resp.ok) {
      const json = await resp.json();
      return {
        authMode: json.authMode ?? 'global',
        cognitoUserPoolId: json.cognitoUserPoolId,
        cognitoClientId: json.cognitoClientId,
        apiBaseUrl: json.apiBaseUrl ?? '',
        jwksUri: json.jwksUri,
      };
    }
  } catch {
    // config.json not available (local dev) — fall through
  }

  // Fallback to Vite build-time env vars (for local dev)
  return {
    authMode: (import.meta.env.VITE_AUTH_MODE as 'global' | 'china') ?? 'global',
    cognitoUserPoolId: import.meta.env.VITE_COGNITO_USER_POOL_ID,
    cognitoClientId: import.meta.env.VITE_COGNITO_CLIENT_ID,
    apiBaseUrl: import.meta.env.VITE_API_BASE_URL ?? '',
  };
}

/**
 * Get runtime config. Caches after first load.
 */
export async function getRuntimeConfig(): Promise<RuntimeConfig> {
  if (_config) return _config;
  if (!_configPromise) {
    _configPromise = fetchRuntimeConfig().then((c) => {
      _config = c;
      return c;
    });
  }
  return _configPromise;
}

// ---- Amplify Initialization (deferred until config is loaded) ----

let _amplifyConfigured = false;

async function ensureAmplifyConfigured(): Promise<void> {
  if (_amplifyConfigured) return;
  const config = await getRuntimeConfig();
  if (config.authMode === 'global' && config.cognitoUserPoolId && config.cognitoClientId) {
    Amplify.configure({
      Auth: {
        Cognito: {
          userPoolId: config.cognitoUserPoolId,
          userPoolClientId: config.cognitoClientId,
          loginWith: {
            username: true,
            email: true,
          },
        },
      },
    });
    _amplifyConfigured = true;
  }
}

// Eagerly start loading config
getRuntimeConfig().then(() => ensureAmplifyConfigured()).catch(() => {});

// ---- Token storage keys (china mode) ----
const ACCESS_TOKEN_KEY = 'openclaw_access_token';
const REFRESH_TOKEN_KEY = 'openclaw_refresh_token';

// ---- Helpers ----

/** Decode a JWT payload without verification (client-side only). */
function decodeJwtPayload(token: string): Record<string, unknown> {
  const parts = token.split('.');
  if (parts.length !== 3) throw new Error('Invalid JWT format');
  const payload = parts[1];
  const decoded = atob(payload.replace(/-/g, '+').replace(/_/g, '/'));
  return JSON.parse(decoded);
}

/** Check whether a JWT is expired (with a 30-second buffer). */
export function isTokenExpired(token: string | null): boolean {
  if (!token) return true;
  try {
    const payload = decodeJwtPayload(token);
    const exp = payload.exp as number | undefined;
    if (exp === undefined) return true;
    // Consider expired 30 seconds before actual expiry to allow for clock skew
    return Date.now() >= (exp - 30) * 1000;
  } catch {
    return true;
  }
}

// ---- China mode helpers ----

async function chinaLogin(username: string, password: string): Promise<{ requireNewPassword: boolean }> {
  const config = await getRuntimeConfig();
  const apiBase = config.apiBaseUrl ?? '';
  const resp = await fetch(`${apiBase}/api/auth/login`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ username, password }),
  });

  const data = await resp.json().catch(() => ({ message: 'Login failed' }));

  // Auth Service returns 403 with FORCE_CHANGE_PASSWORD when password change is required
  if (resp.status === 403 && data?.error?.code === 'FORCE_CHANGE_PASSWORD') {
    // Save username for the change-password flow
    localStorage.setItem('openclaw_pending_username', username);
    return { requireNewPassword: true };
  }

  if (!resp.ok) {
    throw new Error(data?.error?.message ?? data?.message ?? 'Login failed');
  }

  if (data.force_change_pwd) {
    // Store tokens temporarily so change-password can use them
    localStorage.setItem(ACCESS_TOKEN_KEY, data.access_token);
    localStorage.setItem(REFRESH_TOKEN_KEY, data.refresh_token);
    return { requireNewPassword: true };
  }

  localStorage.setItem(ACCESS_TOKEN_KEY, data.access_token);
  localStorage.setItem(REFRESH_TOKEN_KEY, data.refresh_token);
  return { requireNewPassword: false };
}

async function chinaRefreshToken(): Promise<string> {
  const refreshToken = localStorage.getItem(REFRESH_TOKEN_KEY);
  if (!refreshToken) throw new Error('No refresh token');

  const config = await getRuntimeConfig();
  const apiBase = config.apiBaseUrl ?? '';
  const resp = await fetch(`${apiBase}/api/auth/refresh`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ refresh_token: refreshToken }),
  });

  if (!resp.ok) {
    // Refresh failed – clear tokens and force re-login
    localStorage.removeItem(ACCESS_TOKEN_KEY);
    localStorage.removeItem(REFRESH_TOKEN_KEY);
    throw new Error('Token refresh failed');
  }

  const data = await resp.json();
  localStorage.setItem(ACCESS_TOKEN_KEY, data.access_token);
  return data.access_token;
}

async function chinaChangePassword(oldPassword: string, newPassword: string): Promise<void> {
  const config = await getRuntimeConfig();
  const apiBase = config.apiBaseUrl ?? '';
  const token = localStorage.getItem(ACCESS_TOKEN_KEY);

  // In force-change-password flow, we need the username. It's stored
  // in localStorage during the login attempt that triggered the flow.
  const username = localStorage.getItem('openclaw_pending_username') ?? '';

  const resp = await fetch(`${apiBase}/api/auth/change-password`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      ...(token ? { Authorization: `Bearer ${token}` } : {}),
    },
    body: JSON.stringify({ username, old_password: oldPassword, new_password: newPassword }),
  });

  if (!resp.ok) {
    const body = await resp.json().catch(() => ({ message: 'Change password failed' }));
    throw new Error(body?.error?.message ?? body?.message ?? 'Change password failed');
  }

  // Clear pending username after successful password change
  localStorage.removeItem('openclaw_pending_username');
}

// ---- Public API ----

export interface SignInResult {
  requireNewPassword: boolean;
}

/**
 * Sign in with username and password.
 * Returns whether the user must change their password before proceeding.
 */
export async function signIn(username: string, password: string): Promise<SignInResult> {
  const config = await getRuntimeConfig();
  if (config.authMode === 'dev') {
    // Dev mode: store username as token, role determined by username
    localStorage.setItem(ACCESS_TOKEN_KEY, username);
    return { requireNewPassword: false };
  }
  if (config.authMode === 'global') {
    await ensureAmplifyConfigured();
    // Clear any residual Amplify auth state to avoid UserAlreadyAuthenticatedException
    try {
      await amplifySignOut();
    } catch {
      // Ignore — no session to clear
    }
    const result = await amplifySignIn({ username, password });
    const requireNewPassword = result.nextStep?.signInStep === 'CONFIRM_SIGN_IN_WITH_NEW_PASSWORD_REQUIRED';
    return { requireNewPassword };
  }
  return chinaLogin(username, password);
}

/**
 * Change password (used during forced password change on first login).
 */
export async function changePassword(oldPassword: string, newPassword: string): Promise<void> {
  const config = await getRuntimeConfig();
  if (config.authMode === 'global') {
    await ensureAmplifyConfigured();
    const { confirmSignIn } = await import('aws-amplify/auth');
    await confirmSignIn({ challengeResponse: newPassword });
    return;
  }
  return chinaChangePassword(oldPassword, newPassword);
}

/**
 * Get a valid access token, automatically refreshing if expired.
 */
export async function getToken(): Promise<string> {
  const config = await getRuntimeConfig();
  if (config.authMode === 'dev') {
    return localStorage.getItem(ACCESS_TOKEN_KEY) ?? 'dev-token';
  }
  if (config.authMode === 'global') {
    await ensureAmplifyConfigured();
    const session = await fetchAuthSession();
    const token = session.tokens?.idToken?.toString();
    if (!token) throw new Error('No valid session');
    return token;
  }

  // China mode
  const token = localStorage.getItem(ACCESS_TOKEN_KEY);
  if (!token || isTokenExpired(token)) {
    return chinaRefreshToken();
  }
  return token;
}

/**
 * Sign out the current user.
 */
export async function signOut(): Promise<void> {
  const config = await getRuntimeConfig();
  if (config.authMode === 'dev') {
    localStorage.removeItem(ACCESS_TOKEN_KEY);
    return;
  }
  if (config.authMode === 'global') {
    await amplifySignOut();
    return;
  }
  localStorage.removeItem(ACCESS_TOKEN_KEY);
  localStorage.removeItem(REFRESH_TOKEN_KEY);
}

/**
 * Check if the user is currently authenticated (has a non-expired token).
 * Synchronous check — uses cached config. If config hasn't loaded yet, returns false.
 */
export function isAuthenticated(): boolean {
  const config = _config;
  if (!config) return false; // Config not loaded yet

  if (config.authMode === 'dev') {
    return !!localStorage.getItem(ACCESS_TOKEN_KEY);
  }

  if (config.authMode === 'global') {
    // Check if Amplify has stored Cognito tokens in localStorage.
    const clientId = config.cognitoClientId ?? '';
    if (!clientId) return false;
    try {
      for (let i = 0; i < localStorage.length; i++) {
        const key = localStorage.key(i);
        if (key && key.includes(clientId) && key.includes('idToken')) {
          const token = localStorage.getItem(key);
          return !isTokenExpired(token);
        }
      }
    } catch {
      // localStorage not available
    }
    return false;
  }
  const token = localStorage.getItem(ACCESS_TOKEN_KEY);
  return !isTokenExpired(token);
}

export { type RuntimeConfig };
